### PR TITLE
wt88047: defconfig: charger: We only use SMB1360

### PR DESCRIPTION
**Pull request by danielstuart14**
It was building many chargers that aren't compatible with wt88047. Should fix fast charge

### CODE REVIEW

**Comment by kumajaya** [comment]
How not registered driver interferer fast charge? My config file extracted from stock kernel. I don't own all WT88047 variant out there, so I follow stock config just to be safe.

**Comment by danielstuart14** [comment]
Msm8916 defconfig enable all the chargers for it just for compatibility.
Only smb1628 is used on redmi. Also, about fast charge, Ferrari source from
xiaomi hás the changes needed on smb1628 driver

Em sexta-feira, 8 de janeiro de 2016, Ketut P. Kumajaya <
notifications@github.com> escreveu:

> How not registered driver interferer fast charge? My config file extracted
> from stock kernel. I don't own all WT88047 variant out there, so I follow
> stock config just to be safe.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kumajaya/android_kernel_cyanogen_msm8916/pull/6#issuecomment-169932721
> .

## 

daniel p. stuart

**Comment by danielstuart14** [comment]
Smb1360**

Em sexta-feira, 8 de janeiro de 2016, Daniel stuart <
daniel.stuart14@gmail.com> escreveu:

> Msm8916 defconfig enable all the chargers for it just for compatibility.
> Only smb1628 is used on redmi. Also, about fast charge, Ferrari source from
> xiaomi hás the changes needed on smb1628 driver
> 
> Em sexta-feira, 8 de janeiro de 2016, Ketut P. Kumajaya <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> escreveu:
> 
> > How not registered driver interferer fast charge? My config file
> > extracted from stock kernel. I don't own all WT88047 variant out there, so
> > I follow stock config just to be safe.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kumajaya/android_kernel_cyanogen_msm8916/pull/6#issuecomment-169932721
> > .
> 
> ## 
> 
> daniel p. stuart

## 

daniel p. stuart

**Comment by kumajaya** [comment]
Which MSM8916? This kernel config from stock kernel extracted using extract-ikconfig tool http://forum.xda-developers.com/android/software-hacking/how-to-convert-qualcomms-dtb-to-dts-t3221223/post63217945

**Comment by danielstuart14** [comment]
msm8916 defconfig (From qualcomm)

**Comment by HVPereira** [comment]
may be this helps:

http://lists.infradead.org/pipermail/linux-arm-kernel/2015-October/375720.html

(No expert here =()

**Comment by kumajaya** [comment]
Why this pull request so huge now? I have merged Wingtech's Lollipop kernel config and dts related to power supply and charger now.

**Comment by HVPereira** [comment]
It was inserted a long time ago sorry kumajaya!

**Pull request closed without merging**
