### PR TITLE
Some path is not correct in camera_wt8807_v2

### PR DESCRIPTION
**Pull request by ghost**
Maybe someone (especially me) cant build because this typo.
And forget about my Makefile ^.^
I'm sorry if my english is bad.

### CODE REVIEW

**Comment by kumajaya** [comment]
Do you build the kernel inside the kernel source tree?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
Is this wrong method ?

**Comment by kumajaya** [comment]
Maybe something wrong in my source but build a kernel in source tree not recommended. Please read kernel source README file.

**Comment by ghost** [comment]
so i need to add O=output/dir ?

**Comment by slfl** [comment]
yes

**Comment by ghost** [comment]
Thank you :+1:

**Comment by kumajaya** [comment]
Please always build the kernel outside the kernel source tree. Git + in place build is a perfect nightmare :D

**Comment by ghost** [comment]
nightmare is really come to me if add using wildcard :v

**Pull request closed without merging**
